### PR TITLE
drupal vm setup.

### PR DESCRIPTION
**Pull request by lgates**

### CODE REVIEW

**Comment by mikemadison13** [comment]
Hey, I was planning on lando here not drupalvm. Is that ok?

**Comment by charlieartist** [comment]
@mikemadison13 I believe that Lando will also be used here, in order to ensure parity. Also due to the fact that some members of the D4G/GovCon team couldn't get the Drupal VM builds running at all.

**Comment by mikemadison13** [comment]
That's what I assumed, just curious about the drupal vm pr

**Comment by charlieartist** [comment]
@mikemadison13 Hmm. I'll ask them about that tomorrow. After your last merge for GovCon, I pinged Laura, Kirsten, and Jess to try setting up the new local, so we can see how easy it is for contributors to get started.

**Comment by lgates** [comment]
Sorry Karl,

I’m sick and started it but fell asleep during checkout of the GovCon site. Gonna go check it.

**Pull request closed without merging**
